version: "3.8"

services:
  client:
    build: ./client
    ports:
      - "${CLIENT_PORT}:${CLIENT_PORT}"
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=${NODE_ENV}
    depends_on:
      - server
    restart: on-failure

  server:
    build: ./server
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    volumes:
      - ./server:/usr/src/app
    environment:
      - FLASK_ENV=${FLASK_ENV}
    depends_on:
      - db
    restart: on-failure

  tester:
    build:
      context: ./server
      dockerfile: Dockerfile
    command: ["python3", "-m", "pytest"]
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/__pycache__ # prevent caching issues
    depends_on:
      - server
    restart: 'no' # if you wanna test all automatically, you can change it as on-failure, but it little bit annoying.

  db:
    image: mysql:8.3.0
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - db_data:/var/lib/mysql
      - ./server/university_timetable.sql:/docker-entrypoint-initdb.d/10-university_timetable.sql
      - ./server/seed_data.sql:/docker-entrypoint-initdb.d/20-seed_data.sql

  admin:
    image: phpmyadmin
    restart: always
    environment:
      - PMA_ARBITRARY=1
    ports:
      - ${ADMIN_PORT}:80
    depends_on:
      - db

volumes:
  db_data:
